#ifndef COLORMAP_H
#define COLORMAP_H

#include <QVector>
#include <QPixmap>
#include <opencv2/core/core.hpp>

struct Palette {
	// "Tableau 20" colorset, which consists of 10 colors, and their 10 lighter counterparts
	static const QVector<QColor> tableau20;

	// 20 colors generated by iwanthue, H 0-360, C 30-100, L 20-80, random sort
	static const QVector<QColor> iwanthue20;
};

struct Colormap {
	Colormap(const std::array<cv::Vec3b, 256>& map) : map(map) {}

	// convert Mat1b
	cv::Mat3b apply(const cv::Mat1b &source);
	// convert any matrix (includes conversion to Mat1b)
	cv::Mat3b apply(const cv::Mat &source, double scale, double minVal=0.);
	// convert single value
	cv::Vec3b apply(double value, double min, double max);

	const std::array<cv::Vec3b, 256> map;

	// produce QColor from Vec3b (note: assumes RGB, not OpenCV's BGR)
	static QColor qcolor(const cv::Vec3b &color);

	// convert any matrix to Mat1b
	static cv::Mat1b prepare(const cv::Mat &source, double scale, double minVal=0.);

	// convert colormap matrix to pixmap
	static QPixmap pixmap(const cv::Mat3b &source);

	// Magma color map
	static Colormap magma;

	// Viridis color map
	static Colormap viridis;

	// Red to green color map (for score displays, red == bad, green == good)
	static Colormap stoplight, stoplight_mild;
};

#endif
